"""task_requires_meeting_and_report_approval

Revision ID: aec8aa81e7a1
Revises: 91ff22838ff5
Create Date: 2026-07-29 02:37:50.602556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aec8aa81e7a1'
down_revision: Union[str, None] = '91ff22838ff5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting_reports', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    # 既存行があるためNOT NULLにはserver_defaultが必要（Falseで統一）
    op.add_column(
        'tasks',
        sa.Column('requires_meeting', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'requires_meeting')
    op.drop_column('meeting_reports', 'approved_at')
    # ### end Alembic commands ###
